Fix Log4j vulnerability
Unleash/unleash-client-java pull request #146
Opened 2021-12-10 11:28 UTC by emilva

There is a critical vulnerabiltiy in Log4, more information here: https://www.lunasec.io/docs/blog/log4j-zero-day/

2021-12-10 11:31 UTC, chriswk requested changes

2021-12-10 11:31 UTC, chriswk commented on pom.xml
> +        <version.log4j2>2.15.1</version.log4j2>
There's no 2.15.1 yet, I assume you meant 2.15.0 :)
```suggestion
        <version.log4j2>2.15.0</version.log4j2>
```

2021-12-10 11:38 UTC, emilva commented
Yes, you are correct! :)

2021-12-10 11:50 UTC, chriswk approved these changes
Thank you!
:+1:

2021-12-10 11:51 UTC, merged

2021-12-11 17:32 UTC, barkanido commented
Can this be also backported?