Fix: Broken urls and branch names in readme
Unleash/unleash-client-java pull request #155
Opened 2022-04-19 07:15 UTC by deepakchethan

Hello!

I was going through the readme and noticed that some urls are outdated and branch name was still pointing to the old `master` instead of `main` and updated them. Please see if we can update these if it's fine.

Thanks!

2022-04-19 14:16 UTC, Tymek approved these changes
Thx @deepakchethan! I think `.github/workflows/main.yml` and `.github/workflows/publish_javadoc.yml` can also be updated by removing reference to unused branch.

2022-04-19 20:46 UTC, ivarconr approved these changes

2022-04-20 01:41 UTC, deepakchethan commented
> Thx @deepakchethan! I think `.github/workflows/main.yml` and `.github/workflows/publish_javadoc.yml` can also be updated by removing reference to unused branch.

Sure, Thank you for the review. I updated them in https://github.com/Unleash/unleash-client-java/pull/155/commits/d7d6ae78b22fc2d695141439ca6a2f6b3500b022.

2022-04-20 10:01 UTC, thomasheartman requested changes
Super work! Thanks for picking up on this 🙏🏼  I've added a couple of inline suggestions of link updates, so that they point to the actual rendered docs instead of to the github markdown source files. Once that's in, it's all good from my end 😄

2022-04-20 10:01 UTC, thomasheartman commented on README.md
> +Read more about the strategies in [activation-strategy.md](https://github.com/Unleash/unleash/blob/main/website/docs/user_guide/activation-strategies.md).
```suggestion
Read more about the strategies in [the activation strategies documentation](https://docs.getunleash.io/user_guide/activation_strategy).
```

2022-04-20 10:01 UTC, thomasheartman commented on README.md
> +In order to use some of the common activation strategies you must provide a [unleash-context](https://github.com/Unleash/unleash/blob/main/website/docs/user_guide/unleash-context.md).
```suggestion
In order to use some of the common activation strategies you must provide an [Unleash context](https://docs.getunleash.io/user_guide/unleash_context).
```

2022-04-21 04:29 UTC, merged